backend:
  name: git-gateway
  branch: main

media_folder: images

collections:
  - name: news
    label: News Items
    folder: _news
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Body, name: body, widget: text }
